// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prj_JACV_Ejercicio_6.DataContext;

#nullable disable

namespace Prj_JACV_Ejercicio_6.Migrations
{
    [DbContext(typeof(RHDBContext))]
    [Migration("20230903192513_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Analista", b =>
                {
                    b.Property<int>("ID_Analista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Analista"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Analista");

                    b.ToTable("Analistas");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.AreaDesempeno", b =>
                {
                    b.Property<int>("ID_Area_Desempeno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Area_Desempeno"));

                    b.Property<string>("Nombre_Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valor_Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("ID_Area_Desempeno");

                    b.ToTable("AreasDesempeno");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Punto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Analista")
                        .HasColumnType("int");

                    b.Property<int>("ID_Talento")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Analista");

                    b.HasIndex("ID_Talento");

                    b.ToTable("Puntos");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Talento", b =>
                {
                    b.Property<int>("ID_Talento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Talento"));

                    b.Property<int>("ID_Area")
                        .HasColumnType("int");

                    b.Property<string>("NombreTalento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Talento");

                    b.HasIndex("ID_Area");

                    b.ToTable("Talentos");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Punto", b =>
                {
                    b.HasOne("Prj_JACV_Ejercicio_6.Models.Analista", "Analista")
                        .WithMany("Puntos")
                        .HasForeignKey("ID_Analista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prj_JACV_Ejercicio_6.Models.Talento", "Talento")
                        .WithMany("Puntos")
                        .HasForeignKey("ID_Talento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Talento");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Talento", b =>
                {
                    b.HasOne("Prj_JACV_Ejercicio_6.Models.AreaDesempeno", "AreaDesempeno")
                        .WithMany("Talentos")
                        .HasForeignKey("ID_Area")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaDesempeno");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Analista", b =>
                {
                    b.Navigation("Puntos");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.AreaDesempeno", b =>
                {
                    b.Navigation("Talentos");
                });

            modelBuilder.Entity("Prj_JACV_Ejercicio_6.Models.Talento", b =>
                {
                    b.Navigation("Puntos");
                });
#pragma warning restore 612, 618
        }
    }
}
